Fixed turtle cap, anvil gui, lectern, and jukebox
magmafoundation/Magma-1.16.x pull request #103
Opened 2021-04-07 22:20 UTC by kwright02

2021-04-10 08:29 UTC, Hexeption requested changes
Debug code needs removing and all issues that this fixes need to be in the description

2021-04-10 08:29 UTC, Hexeption commented on patches/minecraft/net/minecraft/client/gui/screen/EditBookScreen.java.patch
> ++            Bukkit.getPlayer("Kwright02").sendMessage("Closing the screen.....");
Debug code remove

2021-04-10 08:29 UTC, Hexeption commented on patches/minecraft/net/minecraft/client/gui/screen/EditBookScreen.java.patch
> ++         System.out.println("Saving changes for modified book.");
Debug code remove

2021-04-10 08:29 UTC, Hexeption commented on patches/minecraft/net/minecraft/entity/boss/WitherEntity.java.patch
> ++      Bukkit.getServer().broadcastMessage("Wither boss was damaged by source: " + p_184601_1_.field_76373_n);
More Debug?

2021-04-10 08:29 UTC, Hexeption commented on patches/minecraft/net/minecraft/entity/monster/SlimeEntity.java.patch
> ++         Bukkit.broadcastMessage("Slime/Magma has died, starting removal/split process");
Debug Code

2021-04-10 08:29 UTC, Hexeption commented on patches/minecraft/net/minecraft/entity/monster/SlimeEntity.java.patch
> ++         Bukkit.broadcastMessage("Split: count: " + k + " eventStatus: " + event.isCancelled());
Debug code

2021-04-10 08:29 UTC, Hexeption commented on patches/minecraft/net/minecraft/entity/passive/BeeEntity.java.patch
> ++         Bukkit.broadcastMessage("Hey, a bee was punched: ds: " + p_70097_1_.func_180136_u() + " a: " + p_70097_2_);
Debug code

2021-04-10 08:29 UTC, Hexeption commented on patches/minecraft/net/minecraft/server/MinecraftServer.java.patch
> ++         System.out.println("New difficulty set! d: " + p_147139_1_ + " isNotLocked: " + p_147139_2_);
Debug code

2021-04-18 22:08 UTC, kwright02 reviewed
Changes made

2021-04-18 22:09 UTC, closed without merging